const activities = [
  {
    id: 1,
    name: 'Baseball/Softball',
    imgURL: '',
    season: ['🌼', '🌞', '🍂'],
    minTemp: 15,
    maxTemp: 35,
    maxWind: 15,
    Precipitation: 2,
  },
  {
    id: 2,
    name: 'Basketball',
    imgURL: '',
    season: ['🌞', '🍂'],
    minTemp: 18,
    maxTemp: 35,
    maxWind: 10,
    Precipitation: 2,
  },
  {
    id: 3,
    name: 'Beach volleyball',
    season: ['🌞', '🍂'],
    imgURL: '',
    minTemp: 18,
    maxTemp: 38,
    maxWind: 12,
    Precipitation: 2,
  },
  {
    id: 4,
    name: 'Cycling',
    imgURL: '',
    season: ['🌼', '🌞', '🍂'],
    minTemp: 15,
    maxTemp: 38,
    maxWind: 15,
    Precipitation: 2,
  },
  {
    id: 5,
    name: 'Bouldering',
    season: ['🌼', '🌞', '🍂'],
    imgURL: '',
    minTemp: 15,
    maxTemp: 35,
    maxWind: 20,
    Precipitation: 2,
  },
  {
    id: 6,
    name: 'Skiing/Snow boarding',
    season: ['❄️'],
    imgURL: '',
    minTemp: -20,
    maxTemp: 5,
    maxWind: 20,
    Precipitation: 10,
  },
  {
    id: 7,
    name: 'Cross country skiing',
    season: ['❄️'],
    imgURL: '',
    minTemp: -20,
    maxTemp: 5,
    maxWind: 15,
    Precipitation: 10,
  },
];

export default activities;
